"""empty message

Revision ID: 110b1c69c546
Revises: 531cc96af951
Create Date: 2014-09-17 00:33:06.733580

"""

# revision identifiers, used by Alembic.
revision = '110b1c69c546'
down_revision = '531cc96af951'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbooks', sa.Column('image_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('textbooks', 'image_id')
    ### end Alembic commands ###
