"""empty message

Revision ID: 14eeaf7d918
Revises: 4f1b7e8d4fd5
Create Date: 2014-09-12 00:44:25.958640

"""

# revision identifiers, used by Alembic.
revision = '14eeaf7d918'
down_revision = '4f1b7e8d4fd5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('account_balance', sa.Float(precision=2), nullable=False),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column(u'accounts', sa.Column('permission_level', sa.Integer(), nullable=True))
    op.drop_column(u'customer_supports', 'permission_level')
    op.add_column(u'orders', sa.Column('course', sa.String(length=80), nullable=True))
    op.add_column(u'orders', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.drop_column(u'orders', 'dealine')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'orders', sa.Column('dealine', mysql.DATETIME(), nullable=True))
    op.drop_column(u'orders', 'deadline')
    op.drop_column(u'orders', 'course')
    op.add_column(u'customer_supports', sa.Column('permission_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column(u'accounts', 'permission_level')
    op.drop_table('account_record')
    ### end Alembic commands ###
