"""empty message

Revision ID: 16752b189a8a
Revises: 19c304f256b5
Create Date: 2014-09-20 20:10:29.094285

"""

# revision identifiers, used by Alembic.
revision = '16752b189a8a'
down_revision = '19c304f256b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
