"""empty message

Revision ID: 1bfb66db1f3b
Revises: None
Create Date: 2014-09-08 14:08:46.494994

"""

# revision identifiers, used by Alembic.
revision = '1bfb66db1f3b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
