"""empty message

Revision ID: 445eae9f1633
Revises: 14eeaf7d918
Create Date: 2014-09-17 17:30:51.392918

"""

# revision identifiers, used by Alembic.
revision = '445eae9f1633'
down_revision = '14eeaf7d918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
