"""empty message

Revision ID: 52b034aaaf7d
Revises: 16752b189a8a
Create Date: 2014-09-20 20:13:22.801497

"""

# revision identifiers, used by Alembic.
revision = '52b034aaaf7d'
down_revision = '16752b189a8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
