"""empty message

Revision ID: 531cc96af951
Revises: 14eeaf7d918
Create Date: 2014-09-17 00:32:32.263690

"""

# revision identifiers, used by Alembic.
revision = '531cc96af951'
down_revision = '14eeaf7d918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
